mappings:
  properties:
    id:
      type: long
      index: false
    description:
      type: text
      analyzer: app_french_light
      fields:
        stemmed:
          type: text
          analyzer: app_french_heavy
        autocomplete:
          type: text
          analyzer: app_autocomplete
          search_analyzer: standard
        keywordstring:
          type: text
          analyzer: keyword_analyzer
        edgengram:
          type: text
          analyzer: edge_ngram_analyzer
          search_analyzer: edge_ngram_search_analyzer
        completion:
          type: completion
    numero:
      type: text
      analyzer: standard
    expediteur:
      type: text
      analyzer: app_french_light
      fields:
        stemmed:
          type: text
          analyzer: app_french_heavy
    categorie:
      type: text
    destinataires:
      type: keyword
    services:
      type: keyword
    original:
      type: text
      index: false
    copie:
      type: text
      index: false
    accuse:
      type: boolean
    recommande:
      type: boolean
    date_courrier:
      type: date
      format: strict_date_optional_time||epoch_millis
    url:
      type: text
      index: false
