doctrine:
  orm:
    mappings:
      AcMarche\Bottin:
        is_bundle: false
        type: annotation
        dir: '%kernel.project_dir%/src/AcMarche/Bottin/src/Entity'
        prefix: 'AcMarche\Bottin'
        alias: AcMarche\Bottin
