security:
  providers:
    ville_ldap:
      ldap:
        service: Symfony\Component\Ldap\Ldap
        base_dn: '%env(ACLDAP_DN)%'
        search_dn: '%env(ACLDAP_USER)%'
        search_password: '%env(ACLDAP_PASSWORD)%'
        default_roles: ROLE_USER
        uid_key: sAMAccountName
        extra_fields: ['mail']
    all_users:
      chain:
        providers: ['bottin_user_provider', 'ville_ldap']
  firewalls:

    main:
      provider: ville_ldap
      form_login_ldap:
        service: Symfony\Component\Ldap\Ldap
        search_dn: '%env(ACLDAP_USER)%'
        search_password: '%env(ACLDAP_PASSWORD)%'
        query_string: '(&(|(sAMAccountName={username}))(objectClass=person))'
        dn_string: '%env(ACLDAP_DN)%'
        check_path: 'app_login'
        username_parameter: 'username'
        password_parameter: 'password'
services:

  Symfony\Component\Ldap\Ldap:
    arguments: ['@Symfony\Component\Ldap\Adapter\ExtLdap\Adapter']
  Symfony\Component\Ldap\Adapter\ExtLdap\Adapter:
    arguments:
      - host: '%env(ACLDAP_URL)%'
        port: 636
        encryption: ssl
        options:
          protocol_version: 3
          referrals: false
