mappings:
  properties:
    id:
      type: long
      index: false
    location:
      type: geo_point
    cap:
      type: keyword
    type:
      type: keyword
    centre_ville:
      type: keyword
    pmr:
      type: keyword
    midi:
      type: keyword
    localite:
      type: text
      analyzer: app_french_light
      fields:
        keyword:
          type: keyword
    societe:
      type: text
      analyzer: app_french_light
      fields:
        stemmed:
          type: text
          analyzer: app_french_heavy
        ngram:
          type: text
          analyzer: edge_ngram_analyzer
        edgengram:
          type: text
          analyzer: edge_ngram_analyzer
          search_analyzer: edge_ngram_search_analyzer
    description:
      type: text
      analyzer: app_french_light
      fields:
        stemmed:
          type: text
          analyzer: app_french_heavy
        ngram:
          type: text
          analyzer: edge_ngram_analyzer
    nom:
      type: text
      analyzer: app_french_light
      fields:
        stemmed:
          type: text
          analyzer: app_french_heavy
        ngram:
          type: text
          analyzer: edge_ngram_analyzer
    fonction:
      type: text
      analyzer: app_french_light
      fields:
        stemmed:
          type: text
          analyzer: app_french_heavy
        ngram:
          type: text
          analyzer: edge_ngram_analyzer
    comment1:
      type: text
      analyzer: app_french_light
      fields:
        stemmed:
          type: text
          analyzer: app_french_heavy
        ngram:
          type: text
          analyzer: edge_ngram_analyzer
    comment2:
      type: text
      analyzer: app_french_light
      fields:
        stemmed:
          type: text
          analyzer: app_french_heavy
        ngram:
          type: text
          analyzer: edge_ngram_analyzer
    comment3:
      type: text
      analyzer: app_french_light
      fields:
        stemmed:
          type: text
          analyzer: app_french_heavy
        ngram:
          type: text
          analyzer: edge_ngram_analyzer
    classements:
      properties:
        name:
          type: text
          analyzer: app_french_light
          fields:
            stemmed:
              type: text
              analyzer: app_french_heavy
            ngram:
              type: text
              analyzer: edge_ngram_analyzer
        description:
          type: text
          analyzer: app_french_light
          fields:
            stemmed:
              type: text
              analyzer: app_french_heavy
            ngram:
              type: text
              analyzer: edge_ngram_analyzer
    secteurs:
      type: text
      analyzer: app_french_light
      fields:
        stemmed:
          type: text
          analyzer: app_french_heavy
        ngram:
          type: text
          analyzer: edge_ngram_analyzer
    name:
      type: text
      analyzer: app_french_light
      fields:
        stemmed:
          type: text
          analyzer: app_french_heavy
        ngram:
          type: text
          analyzer: edge_ngram_analyzer
    created_at:
      type: date
    updated_at:
      type: date
    image:
      type: text

