# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
  bottin.api_key: '%env(BOTTIN_CLEF_GOOGLE)%'
  bottin.cp_default: '6900'
  router.request_context.host: 'bottin.local'
  router.request_context.scheme: 'http'
  bottin.url_update_fiche: '%env(BOTTIN_URL_UPDATE_FICHE)%'
  bottin.url_update_category: '%env(BOTTIN_URL_UPDATE_CATEGORY)%'

services:
  # default configuration for services in *this* file
  _defaults:
    # automatically injects dependencies in your services
    autowire: true
    # automatically registers your services as commands, event subscribers, etc.
    autoconfigure: true
    # this means you cannot fetch services directly from the container via $container->get()
    # if you need to do this, you can override this setting on individual services
    public: false
    bind:
      $clefGoogle: '%env(BOTTIN_CLEF_GOOGLE)%'

  # makes classes in src/App available to be used as services
  # this creates a service per class whose id is the fully-qualified class name
  AcMarche\Bottin\:
    resource: '../src/*'
    # you can exclude directories or files
    # but if a service is unused, it's removed anyway
    exclude: '../src/{Entity,Tests}'

  AcMarche\Bottin\Namer\DirectoryNamer:
    public: true

  AcMarche\Bottin\Hades\HadesRepository:
    $url: '%env(HADES_URL)%'

  Symfony\Component\Ldap\Ldap:
    arguments: ['@Symfony\Component\Ldap\Adapter\ExtLdap\Adapter']
  Symfony\Component\Ldap\Adapter\ExtLdap\Adapter:
    arguments:
      - host: '%env(ACLDAP_URL)%'
        port: 636
        encryption: ssl
        options:
          protocol_version: 3
          referrals: false

  AcMarche\Bottin\Security\StaffLdap:
    $host: '%env(ACLDAP_URL)%'
    $dn: '%env(ACLDAP_DN)%'
    $user: '%env(ACLDAP_USER)%'
    $password: '%env(ACLDAP_PASSWORD)%'
